[package]
name = "padamo-stft"
version = "0.1.0"
edition = "2021"

[lib]
name = "padamosfft"
crate-type = ["dylib"]


[dependencies]
abi_stable = "0.11.3"
padamo-api = { path = "../padamo-api" }
rayon = "1.8.1"
ndarray = { version = "0.15.6", features = ["rayon"] }
rustfft = "6.2.0"
